spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campusmarketplace
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Alvin11David
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: alvin69david@gmail.com
    password: vxal hjkz vcyo chun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  jwt:
    secret: campus-marketplace-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
  frontend:
    url: http://localhost:3000

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:campusmarketplace
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
